# -*- coding: utf-8 -*- #
# frozen_string_literal: true

# DO NOT EDIT - AUTOGENERATED
#
# This Rouge lexer file has been autogenerated by convert_pygments_regex_lexer
# from Python's regex lexer <class '__main__.MMTLexer'>

module Rouge
	module Lexers
		class MMT < RegexLexer
			title 'mmt'
			desc <<-DESC

	Pygments Lexer for MMT Surface Syntax (.mmt)

	The MMT project can be found at https://uniformal.github.io/.
	
DESC
			tag 'mmt'
			mimetypes 'text/plain'
			filenames '*.mmt'
			state :root do
				rule %r/\s/im do
					token Text::Whitespace
				end
				rule %r/(meta)(?= )/im do
					token Keyword::Declaration
					push :expectMD
					push :metaAnnotation
				end
				rule %r/(namespace)(\s+)(\S+)(\s*)(❚)/im do
					groups Keyword::Namespace,Text::Whitespace,Text,Text::Whitespace,Text
				end
				rule %r/(import)(\s+)(\S+)(\s+)(\S+)(\s*)(❚)/im do
					groups Keyword::Namespace,Text::Whitespace,Name::Namespace,Text::Whitespace,Text,Text::Whitespace,Text
				end
				rule %r/theory\b/im do
					token Keyword::Declaration
					push :theoryHeader
				end
				rule %r/(implicit)(\s+)(view)\b/im do
					groups Keyword::Declaration,Text::Whitespace,Keyword::Declaration
					push :viewHeader
				end
				rule %r/(view)\b/im do
					token Keyword::Declaration
					push :viewHeader
				end
				rule %r/\/T .*?❚/im do
					token Comment::Multiline
				end
				rule %r/\/\/.*?❚/im do
					token Comment::Multiline
				end
			end
			state :expectMD do
				rule %r/(\s*)(❚)/im do
					groups Text::Whitespace,Text
pop!(1)
				end
			end
			state :expectDD do
				rule %r/(\s*)(❙)/im do
					groups Text::Whitespace,Text
pop!(1)
				end
			end
			state :expectOD do
				rule %r/(\s*)(❘)/im do
					groups Text::Whitespace,Text
pop!(1)
				end
			end
			state :metaAnnotation do
				rule %r/(\s*)(.*?)(\s+)/im do
					groups Text::Whitespace,Name::Constant,Text::Whitespace
					push :metaAnnotationValue
				end
			end
			state :metaAnnotationValue do
				rule %r/\?[^ ❘❙❚]*/im do
					token Text
pop!(2)
				end
				rule %r/[^❘❙❚]*/im do
					token Text
pop!(2)
				end
			end
			state :theoryHeader do
				rule %r/\s/im do
					token Text::Whitespace
				end
				rule %r/(\S+)(\s*)(:)(\s*)(\S+)(\s*)(=)/im do
					groups Name::Variable,Text::Whitespace,Punctuation,Text::Whitespace,Name::Variable,Text::Whitespace,Punctuation
					push :moduleBody
				end
				rule %r/(\S+)(\s*)(=)/im do
					groups Name::Variable,Text::Whitespace,Punctuation
					push :moduleBody
				end
			end
			state :viewHeader do
				rule %r/\s/im do
					token Text::Whitespace
				end
				rule %r/(\S+)(\s*)(:)(\s*)(\S+)(\s*)(->|→)(\s*)(\S+)(\s*)(=)/im do
					groups Name::Variable,Text::Whitespace,Punctuation,Text::Whitespace,Name::Variable,Text::Whitespace,Punctuation,Text::Whitespace,Name::Variable,Text::Whitespace,Punctuation
					push :moduleBody
				end
			end
			state :moduleBody do
				rule %r/\s/im do
					token Text::Whitespace
				end
				rule %r/\/T .*?❙/im do
					token Comment::Multiline
				end
				rule %r/\/\/.*?❙/im do
					token Comment::Multiline
				end
				rule %r/(meta)(?= )/im do
					token Keyword::Declaration
					push :expectDD
					push :metaAnnotation
				end
				rule %r/(include)(\s+)([^❙]+)(❙)/im do
					groups Keyword::Namespace,Text::Whitespace,Text,Text
				end
				rule %r/(constant)(\s+)([^\s:❘❙]+)/im do
					groups Keyword::Declaration,Text::Whitespace,Name::Constant
					push :constantDeclaration
				end
				rule %r/(rule)(\s+)([^❙]+)(\s*)(❙)/im do
					groups Keyword::Namespace,Text::Whitespace,Text,Text::Whitespace,Text
				end
				rule %r/theory\b/im do
					token Keyword::Declaration
					push :theoryHeader
				end
				rule %r/(#+)([^❙]+)(❙)/im do
					groups Literal::String::Doc,Literal::String::Doc,Text
				end
				rule %r/[^\s:❘❙❚]+/im do
					token Name::Constant
					push :constantDeclaration
				end
				rule %r/❚/im do
					token Text
pop!(2)
				end
			end
			state :constantDeclaration do
				rule %r/\s/im do
					token Text::Whitespace
				end
				rule %r/:/im do
					token Punctuation
					push :expression
				end
				rule %r/=/im do
					token Punctuation
					push :expression
				end
				rule %r/#/im do
					token Punctuation
					push :notationExpression
				end
				rule %r/(@)([^❘❙]+)/im do
					groups Punctuation,Name::Constant
				end
				rule %r/role\b/im do
					token Keyword
					push :expression
				end
				rule %r/(meta)(?= )/im do
					token Keyword::Declaration
					push :metaAnnotation
				end
				rule %r/\/\/[^❘❙]*/im do
					token Comment::Multiline
				end
				rule %r/❘/im do
					token Text
				end
				rule %r/❙/im do
					token Text
pop!(1)
				end
			end
			state :notationExpression do
				rule %r/\s+/im do
					token Text::Whitespace
				end
				rule %r/\d+/im do
					token Literal::String::Interpol
				end
				rule %r/%?((I|V|L)\d+[Td]*)(_(I|L)\d+[Td]*)*/im do
					token Literal::String::Interpol
				end
				rule %r/…/im do
					token Literal::String::Interpol
				end
				rule %r/(\bprec)(\s+)(-?\d+)/im do
					groups Keyword,Text::Whitespace,Literal::Number::Integer
pop!(1)
				end
				rule %r/([^\s\d…❘❙]+)/im do
					token Literal::String::Symbol
				end
				rule %r/(?=[❘❙])/im do
					token Text::Whitespace
pop!(1)
				end
			end
			state :expression do
				rule %r/\s/im do
					token Text::Whitespace
				end
				rule %r/[^❘❙]+/im do
					token Text
pop!(1)
				end
			end
		end
	end
end
